### ISSUE TITLE
Plugin doesn't work on fixed mode

### ISSUE THREAD

**Issue by orlp** [SyntaxBlitz/osrs-shattered-relics-fragment-presets#1]
When playing in fixed mode the interface is not on screen:

![image](https://user-images.githubusercontent.com/202547/151007636-0c136f38-82e1-4852-b10b-db3c0273c3b1.png)

**Comment by VibeEly** [comment]
I swapped it to the other side by adding 620 pixels to the X axis. It's "ugly" but works exactly as expected.

ShatteredRelicsFragmentPresetsSidebarOverlayPanel.java

[ShatteredRelicsFragmentPresetsSidebarOverlayPanel.txt](https://github.com/SyntaxBlitz/osrs-shattered-relics-fragment-presets/files/7935881/ShatteredRelicsFragmentPresetsSidebarOverlayPanel.txt)
[shattered_relics_fragment_presetsb.zip](https://github.com/SyntaxBlitz/osrs-shattered-relics-fragment-presets/files/7935921/shattered_relics_fragment_presetsb.zip)

**Comment by SyntaxBlitz** [comment]
fixed in #4
