### ISSUE TITLE
Incorrect icon showing up

### ISSUE THREAD

**Issue by SMccoombes** [SyntaxBlitz/osrs-shattered-relics-fragment-presets#13]
I have Unholy Ranger, Unholy Wizard and Praying Respects active. However the icon is only showing Drakan's Touch (2). It should say Drakan's Touch (3). The client still says Drakan's Touch (3) in the set effects interface.

**Comment by SyntaxBlitz** [comment]
I thought I noticed something like this, but when I turned off the plugin and restarted the client, the problem persisted. Could you confirm that this bug only happens with this plugin active?

**Comment by SMccoombes** [comment]
Sorry. I sent this to the wrong plugin. It was another one that was causing the issue.
