### ISSUE TITLE
Presets not highlighting in latest version of game/client

### ISSUE THREAD

**Issue by Kinomora** [SyntaxBlitz/osrs-shattered-relics-fragment-presets#14]
Feb 9th update - Rev 203
Runelite 1.8.11

Selecting a preset with no filters does not highlight runes or scroll to them anymore :c

**Comment by TaylorAbraham** [comment]
This is likely because of the main game client update that added a "Unequip all" button

**Comment by SyntaxBlitz** [comment]
update landed
