### ISSUE TITLE
No panel rendered

### ISSUE THREAD

**Issue by gricey432** [SyntaxBlitz/osrs-shattered-relics-fragment-presets#22]
Thanks for the plugin!

I've just installed it but can't get it to work.
v1.5

I'm in resizable mode. No panel shows up. I've rebooted, played with the offsets.
Ended up also having an issue where it just blocked the whole game when the plugin was enabled, and I couldn't click anywhere while the fragments view was open. Could reliably fix this by disabling the plugin and reproduce it again by reenabling the plugin.

Sorry I can't give a clearer ticket / better repro. I'll keep trying it out and report back if I find anything to help narrow it down.

**Comment by SyntaxBlitz** [comment]
thanks for reporting! this is a bug introduced in v1.5 when there are no presets configured.

I'm working on pushing out a fix now. In the meantime, you can manually add a preset to the configuration file (`settings.properties` somewhere in your RL install):

```
io.tja.osrs.shattered_relics_fragment_presets.v1.all_presets=[{"fragments"\:["Unholy Warrior"],"name"\:"Sample preset"}]
```

just make sure not to delete all your presets until you've upgraded to v1.6.

apologies for the issue!

**Comment by SyntaxBlitz** [comment]
#23 is now in plugin-hub master, closing this issue. Thanks again for reporting @gricey432!
