### ISSUE TITLE
Fragment presents showing off screen

### ISSUE THREAD

**Issue by BigBinotte** [SyntaxBlitz/osrs-shattered-relics-fragment-presets#9]
When opening the fragments menu, a corner of the presets are visible on the top left of the screen, making it impossible to access the preset.
![Fragment_Preset](https://user-images.githubusercontent.com/55589663/151676364-f95fbd63-ddbd-44e0-9ad1-47a52caa081c.jpg)

**Comment by SyntaxBlitz** [comment]
resolved in newest update
